# Generated by Django 4.2.1 on 2023-07-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConsultorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('num_licencia', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=100)),
            ],
        ),
    ]
